### ISSUE TITLE
Unable to edit models

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/baw-server#496] opened 2020-10-01 04:30 UTC
Attempting to edit/update a model will cause the server to return a 500 error. This seems to stem from the permitting params set in the model controller denying the ability to send the `id` parameter. The list of currently known broken models are the following:

- [ ] Site
- [ ] Project
- [ ] Region

## Example Request 1:
Url: `http://localhost:3000/projects/1/sites/103`
Method: `PATCH`
Request Payload:
```json
{
  "id":103,
  "name":"asdfasdfasdf",
  "description":"dfdfggdfg",
  "project_ids":[1],
  "region_id":null,
  "latitude":null,
  "longitude":null,
  "tzinfo_tz":"Australia/Brisbane",
  "notes":null
}
```
Response:
![image](https://user-images.githubusercontent.com/3955116/94768164-f48fd280-03f1-11eb-9409-15dddce65b00.png)

## Example Request 2:
Url: `http://localhost:3000/projects/1`
Method: `PATCH`
Request Payload:
```json
{
  "id":1,
  "name":"Project 1",
  "description":"Custom testing project",
  "site_ids":[1,2,3],
  "region_ids":[1,2,3],
  "notes":null
}
```
Response:
![image](https://user-images.githubusercontent.com/3955116/94768333-80096380-03f2-11eb-8548-518f2d6a9ff0.png)

**Comment by atruskie** [comment] 2020-10-14 10:40
wontfix - behaving as intended in `development` environment. 

I have changed staging though so it will be consistent with development  (see https://github.com/QutEcoacoustics/baw-server/commit/a3b444748edb9d94670205e79a4fbf533d4210b3) and we will eventually also change prod as well (#499)

**Closed by atruskie** 2020-10-14 10:40 UTC
Labels: API, bug
